Added nginx dockerfile generator
digitalocean/nginxconfig.io pull request #171
Opened 2020-09-25 09:17 UTC by alexmanno

## What issue does this relate to?
- https://github.com/digitalocean/nginxconfig.io/issues/137

### What should this PR do?
- generate nginx dockerfile with generated configurations

2020-09-26 10:19 UTC, MattIPv4 requested changes
I don't think this should use a .conf file, or use the toConf logic. Dockerfiles don't have nested logic like nginx files do really, so it seems confusing to make it rely on that.

Instead, I think it'd be far better to create a file at `src/nginxconfig/generators/ext/docker.js` which directly returns (via a function) the contents of the extra Docker file.

2020-09-26 10:19 UTC, MattIPv4 commented on src/nginxconfig/templates/global_sections/docker.vue
> +                                {{ i18n.templates.globalSections.docker.dockerServer }}
We should give a better explanation here of why a user of the tool may want to check this? Perhaps `Include Dockerfile to run nginx with Docker` as the copy used here?

2020-09-26 10:19 UTC, MattIPv4 commented on src/nginxconfig/templates/global_sections/docker.vue
> +                <label class="label">{{ i18n.templates.globalSections.docker.dockerServer }}</label>
For this copy, let's keep it simple based on what it's actually doing. We're not enabling any Docker configuration options, just enabling a Dockerfile to be added, so let's just use `Dockerfile` as the copy here?

2020-09-26 10:19 UTC, MattIPv4 commented on src/nginxconfig/templates/global_sections/index.js
> +export { default as Docker } from './docker';
```suggestion
export { default as Docker } from './docker';
export { default as Tools } from './tools';
```
Tools is a bit of a tool-meta tab, so we should put config generation tabs before it :)

2020-09-26 10:19 UTC, MattIPv4 commented on package-lock.json
>        "resolved": "https://registry.npmjs.org/vue-select/-/vue-select-3.10.8.tgz",
No changes were made to the packages in package.json, so please revert the changes to package-lock.json.

2020-09-28 07:39 UTC, alexmanno commented
@MattIPv4 Thank you for suggestion! I applied your suggestion, can you review them? Thanks again

2020-09-28 11:40 UTC, MattIPv4 requested changes
Looking good, just some cleanup :)

2020-09-28 11:40 UTC, MattIPv4 commented on src/nginxconfig/generators/to_conf.js
> +const recurse = (entriesOrObject, depth, endLine = ';') => {
```suggestion
const recurse = (entriesOrObject, depth) => {
```
This change can be reverted

2020-09-28 11:40 UTC, MattIPv4 commented on src/nginxconfig/generators/to_conf.js
> +            retVal += indent + (item[0] + keyValIndent + val).trim() + (item[0].startsWith('#') ? '' : endLine) + '\n';
```suggestion
            retVal += indent + (item[0] + keyValIndent + val).trim() + (item[0].startsWith('#') ? '' : ';') + '\n';
```
This change can be reverted

2020-09-28 11:40 UTC, MattIPv4 commented on src/nginxconfig/templates/global_sections/docker.vue
> +        },
```suggestion
```
This watcher isn't needed, as Dockerfile is global only in the implementation.

2020-09-28 11:40 UTC, MattIPv4 commented on src/nginxconfig/i18n/en/common.js
> +	docker: 'Dockerfile',
```suggestion
	docker: 'Docker',
```
Lets keep the tab named 'Docker' so it can potentially be used for more in the future

2020-09-28 11:40 UTC, MattIPv4 commented on src/nginxconfig/i18n/en/templates/global_sections/docker.js
> +    dockerfile: `Include ${common.docker} to run nginx with Docker`,
```suggestion
    dockerfile: `Include Dockerfile to run nginx with ${common.docker}`,
```
Update to string based on above change to common

2020-09-28 14:41 UTC, alexmanno commented
@MattIPv4 Committed your suggestions, thank you!

2020-10-08 14:43 UTC, MattIPv4 approved these changes
Lgtm, thank you!

2020-10-08 14:43 UTC, merged