Feature/pt br translation
digitalocean/nginxconfig.io pull request #202
Opened 2020-12-18 19:44 UTC by fcpimenta

## Type of Change

- Add Portuguese Brazilian translation

## What issue does this relate to?

- N/A

2020-12-21 15:34 UTC, MattIPv4 commented
👋 Tyvm for the PR, @fcpimenta!

Could you rebase this against lastest master when you have a second -- we just merged a few new i18n strings and a tool to help check i18n packs :)

2020-12-21 19:33 UTC, fcpimenta commented
> 👋 Tyvm for the PR, @fcpimenta!
> 
> Could you rebase this against lastest master when you have a second? -- we just merged a few new i18n strings and a tool to help check i18n packs :)

Hi Matt! I've already rebased my fork. Could you please check if all things are ok?

2020-12-21 19:34 UTC, MattIPv4 commented
It looks like this branch specifically still needs to be rebased against your fork's master branch

2020-12-21 19:45 UTC, fcpimenta commented
Branch rebased.

2020-12-21 20:58 UTC, MattIPv4 requested changes
Ty for the rebase :)

Could you export the pack in `src/nginxconfig/i18n/index.js`, please?

This should let the CI then begin to validate all the pack translation keys are present.

2020-12-21 22:07 UTC, fcpimenta commented
I think the issues were corrected.

2020-12-22 01:37 UTC, botreview approved these changes
LGTM

2020-12-22 16:44 UTC, MattIPv4 requested changes
Tyvm!! Just a few small things :)

2020-12-22 17:34 UTC, fcpimenta commented on src/nginxconfig/i18n/pt-br/common.js
> +	logging: 'Logs',
I've verified all indentation. Here there is no error.

2020-12-22 21:09 UTC, MattIPv4 commented on src/nginxconfig/i18n/pt-br/common.js
> +	logging: 'Logs',
Weird, looks like there were some tabs instead of spaces, just committed a quick fix

2020-12-22 21:28 UTC, MattIPv4 approved these changes
Lgtm, tyvm!

2020-12-22 21:29 UTC, merged

2020-12-23 16:46 UTC, MattIPv4 commented
Hey, @fcpimenta - Thanks a ton for this sweet PR! 😄

Would you please shoot me an email when you get a chance?
mcowley at digitalocean dot com 🎉