Add French translations
digitalocean/nginxconfig.io pull request #214
Opened 2021-01-19 12:26 UTC by mphschmitt

## Type of Change

- Add French translations

## What issue does this relate to?

- None

### What should this PR do?

- Add French translations

2021-01-19 15:49 UTC, MattIPv4 requested changes
Two very minor things, otherwise lgtm, thank you very much for doing this!

2021-01-19 15:49 UTC, MattIPv4 commented on src/nginxconfig/i18n/fr/common.js
> +    path: 'chemin',
```suggestion
    path: 'Chemin',
```
Uppercase first letter?

2021-01-19 15:49 UTC, MattIPv4 commented on src/nginxconfig/i18n/fr/common.js
> +    reverseProxyLower: 'reverse proxy',
Can these be translated?

2021-01-19 15:49 UTC, MattIPv4 commented
cc @moniang if you're lurking, `French` needs translating to Chinese 😛 💙

2021-01-19 16:48 UTC, moniang commented
> cc @moniang如果您潜伏，`French`需要翻译成中文😛 💙

`法语`

2021-01-19 16:48 UTC, moniang commented
> cc @moniang if you're lurking, `French` needs translating to Chinese 😛 💙

`法语`

2021-01-19 17:12 UTC, mphschmitt commented on src/nginxconfig/i18n/fr/common.js
> +    path: 'chemin',
Done.

2021-01-19 17:12 UTC, mphschmitt commented on src/nginxconfig/i18n/fr/common.js
> +    reverseProxyLower: 'reverse proxy',
Done.

2021-01-19 21:07 UTC, MattIPv4 approved these changes
Lgtm, thanks again! 💙

2021-01-19 21:08 UTC, merged

2021-01-20 11:50 UTC, MattIPv4 commented
Hey, @mphschmitt - Thanks a ton for this sweet PR! 😄

Would you please shoot me an email when you get a chance?
mcowley at digitalocean dot com 🎉