Fix broken configurations using modules that are enabled but not included
digitalocean/nginxconfig.io pull request #244
Opened 2021-03-26 17:25 UTC by 2ndkauboy

## Type of Change

Bugfix

## What issue does this relate to?

Fixes #243

2021-03-26 17:26 UTC, 2ndkauboy commented on src/nginxconfig/generators/conf/nginx.conf.js
> +
I'm not really familiar with this type of template files, but I hope I copied the similar code for enabled sites correctly.

2021-03-26 18:08 UTC, MattIPv4 requested changes

2021-03-26 18:08 UTC, MattIPv4 commented on src/nginxconfig/generators/conf/nginx.conf.js
> +    ].filter(x => x.length)]);
```suggestion
    config['# Load modules'] = '';
    config.include = `${global.nginx.nginxConfigDirectory.computed.replace(/\/+$/, '')}/modules-enabled/*`;
```
This is outside the HTTP context, so you'll just want to mutate the main config object. :)

I'm also not sure why the modularized structure toggle for the nginxconfig output would affect whether core nginx modules need to be loaded or not? I feel they will always need to be loaded?

2021-03-29 15:20 UTC, MattIPv4 approved these changes
lgtm, ty

2021-03-29 15:21 UTC, merged