Improve mobile styling for the presets panel button group
digitalocean/nginxconfig.io pull request #300
Opened 2021-09-29 21:01 UTC by nadir

This patch fixes the styling for the buttons in the preset panel

Here's how it looks now:
![image](https://user-images.githubusercontent.com/79141224/135347705-6e65d1eb-c022-4f53-9d75-8397527a403b.png)

Compared to before:
![image](https://user-images.githubusercontent.com/79141224/135347751-e190ea73-4be7-43ef-8365-0c00f2dca20e.png)

2021-09-29 21:34 UTC, MattIPv4 requested changes
👋 This is creating some visual oddities on desktop at different resolutions:

Here the final button is a different size and out of proportion with the other buttons:
![image](https://user-images.githubusercontent.com/12371363/135351572-dfdf466d-ac97-4ebe-aa02-67b0641f19f6.png)

An even worse example of this can be see here, where we have one _giant_ button, and one _tiny_ button:
![image](https://user-images.githubusercontent.com/12371363/135351640-ed02b148-1f25-4f81-b5f7-0549a10dbee9.png)

This is also apparent on mobile at certain resolutions, where one button becomes large and the other is small:
![image](https://user-images.githubusercontent.com/12371363/135351747-c5ebb1f9-6e95-40fd-bd6d-991caf40623e.png)

2021-09-29 21:34 UTC, MattIPv4 commented on src/nginxconfig/scss/_panel.scss
> +        flex: 0;
```suggestion
      
        &:last-child {
          flex: 0;
        }
```
This is scss, so selectors should be nested

2021-09-29 21:34 UTC, MattIPv4 commented on src/nginxconfig/scss/_panel.scss
> +      justify-content: start;
```suggestion
      justify-content: flex-start;
```
`start` has limited support, `flex-start` is preferred

2021-09-29 22:30 UTC, nadir commented
Okay maybe using flex-grow was a bad idea (it looks like a masonry ui). Maybe I should just remove the original space-between property ? 

it doesn't look so bad on desktop:
![image](https://user-images.githubusercontent.com/79141224/135357373-ce72aa7b-fc20-42db-86ad-7ee94d7654e2.png)
or mobile:
![image](https://user-images.githubusercontent.com/79141224/135357440-78a9c659-e6c3-4d01-9cbc-e3a8534f8485.png)

2021-10-02 12:38 UTC, MattIPv4 commented
I think we want to keep space-between on desktop for sure, it results in a more balanced UI -- maybe use a media query so you're only removing it on mobile viewports?

2021-11-17 19:36 UTC, closed without merging