refactor: Better button description for view modes
digitalocean/nginxconfig.io pull request #307
Opened 2021-10-03 13:57 UTC by LucaTanks

## Type of Change

Language File

## What issue does this relate to?

N/A

### What should this PR do?

Change wording of the view modes button to be easily understandable

### What are the acceptance criteria?

**Checks Needed:**
- Spelling
- Translated to other languages
- Button sizing adapts correctly

2021-10-04 10:32 UTC, MattIPv4 requested changes

2021-10-04 10:32 UTC, MattIPv4 commented on src/nginxconfig/i18n/en/templates/app.js
> +    splitColumnMode: 'Side by side mode',
```suggestion
    splitColumnMode: 'Side-by-side mode',
```
'Side-by-side' should be hyphenated, please

2021-10-04 15:35 UTC, MattIPv4 approved these changes
LGTM, ty

2021-10-04 15:37 UTC, merged

2021-10-05 13:18 UTC, MattIPv4 commented
Hey, @LucaTanks - Thanks a ton for this PR! 😄

Would you please shoot me an email when you get a chance?
mcowley at digitalocean dot com 🎉

2021-10-05 15:30 UTC, LucaTanks commented
Hi, could you add the `hacktoberfest-accepted` label?

2021-10-05 15:31 UTC, MattIPv4 commented
This repo is already participating in Hacktoberfest, so you should be good to go as this PR has been merged