feat: Global performance improves, add no-cache for HTML
digitalocean/nginxconfig.io pull request #366
Opened 2022-06-12 12:24 UTC by chenyhd

## Type of Change

- **Build Scripts:** add `Cache-Control: no-cache` for HTML source to improve the performance

### What should this PR do?
Global performance improves, add no-cache for HTML

### What are the acceptance criteria?

These changes will add `Cache-Control: no-cache` for website HTML

#### Environmental preparation
1. Nginx website nginx location config
```
listen      80;
# ...
 set                     $base /var/www/example.com;
 root                    $base/public;
 location / {
     try_files $uri $uri/ /index.html;
 }
```
2. Create index.html in `/var/www/example.com/cache-test` and input anything like:
```
<h1>Caching Test</h1>
```
3. In order to prevent the influence of successive operations, please use incognito mode

#### previous behavior
1. When you visit `localhost` with Chrome first time
You will get `200` status code
2. `F5` this page
You will get `304` status code
3. **When you open a new tab and  visit `localhost:8080`**
You will get `200` status code with a cache
![image](https://user-images.githubusercontent.com/18431131/173232622-3c7a6088-67fb-4bb7-be9a-9c9397787b6f.png)

#### Current behavior
Nginx config change to
```
listen      80;
# ...
 set                     $base /var/www/example.com;
 root                    $base/public;

# This commit chages
location ~* \.(?:html)$ {
    add_header Cache-Control "no-cache";
    access_log off;
}

 location / {
     try_files $uri $uri/ /index.html;
 }
```

1. When you visit `localhost` with Chrome first time
You will get `200` status code
2. `F5` this page
You will get `304` status code
3. **When you open a new tab and  visit `localhost:8080`**
You will get `304` status code

UI Changes:

Before:
![image](https://user-images.githubusercontent.com/18431131/173232954-ffffbf00-912e-4f7c-a535-528a08ee214b.png)

After:
![image](https://user-images.githubusercontent.com/18431131/173232977-39e079b7-882f-44e2-a8aa-47510ce33fe1.png)
![image](https://user-images.githubusercontent.com/18431131/173233011-b33b04bd-697b-4d74-b8c7-65c90e52f2b7.png)

2022-06-12 12:38 UTC, chenyhd commented
### Add some information

- [How no-cache work](https://developer.mozilla.org/en-US/docs/Web/HTTP/Caching#force_revalidation)
- [Chrome behaviors](https://stackoverflow.com/questions/26166433/how-to-prevent-request-that-returns-304#:~:text=Naturally%2C%20all%20resources%20were%20served%20with%20200%20codes%20on%20first%20page%20load.%20Thereafter%2C%20testing%20in%20Chrome%20or%20Firefox%20installs%20with%20default%20settings%2C%20I%20observed%20that%3A)

> 
- If you refresh the page via the F5 key or the Refresh button, the page and all resources revalidate (i.e. a request is made to the server for each resource and a 304 returned).
- If you return to the page via a link or entering the URL into the URL bar in a new tab, then no revalidation is done (i.e. no requests are made).
- In Chrome, if you refresh the page by selecting the URL bar and pressing Enter, the page itself revalidates but no other resources do. In Firefox, neither the page nor resources revalidate.

2022-06-12 13:10 UTC, MattIPv4 commented
👋 I'm not sure what you're trying to achieve here, but setting a no-cache header is not going to improve cache performance -- it will in fact do the opposite, it will tell the browser to never cache the file locally and always make a fresh request to the origin (NGINX) to get the file.

2022-06-12 13:12 UTC, MattIPv4 commented
If you want to be able to customise the cache lifetime of HTML files, instead of just adding a checkbox that forces them to never be cached, I'd suggest mirroring how we set cache lifetimes for other asset types already.

2022-06-13 06:47 UTC, chenyhd commented
> I'm not sure what you're trying to achieve here

A: When we deploy a new frontend version the client will receive the latest changes in time

> but setting a no-cache header is not going to improve cache performance -- it will in fact do the opposite, 

A: My understanding is skewed, I thought it was related to "performance" rather than "improving performance". 

> it will tell the browser to never cache the file locally and always make a fresh request to the origin (NGINX) to get the file.

> If you want to be able to customise the cache lifetime of HTML files, instead of just adding a checkbox that forces them to never be cached, I'd suggest mirroring how we set cache lifetimes for other asset types already.

Let me provide some example:

1.[DigitalOcean NGINXConfig](https://www.digitalocean.com/community/tools/nginx)
`cache-control: max-age=0`
![image](https://user-images.githubusercontent.com/18431131/173293891-9474cba9-d9e1-4c8b-b7b5-ff5a63acd7bf.png)

2.[Google](https://www.google.com/)
`cache-control: private, max-age=0`
![image](https://user-images.githubusercontent.com/18431131/173294017-a14bc5f4-cf16-4618-8142-debc37660866.png)


3.[Amazon](https://www.amazon.com/)
`cache-control: no-cache`
![image](https://user-images.githubusercontent.com/18431131/173294525-d4f39ccf-c0ac-466f-9e16-1243670f1e61.png)

HTML is special, If HTML is changed that means related CSS and JS need to be refreshed, If HTML isn't changed that means get CSS and JS from the local cache and follow the expiration setting

`max-age=0` and `no-cache` have the same effect

2022-06-13 11:00 UTC, MattIPv4 commented
Ah okay, I see what you are trying to do now -- could we name this feature "Disable HTML caching" instead then?

2022-06-13 12:40 UTC, chenyhd commented
I have changed it to "Disable HTML caching"
![image](https://user-images.githubusercontent.com/18431131/173355413-82d590b3-7e04-43a6-af4c-10ea747cccc1.png)

2022-06-14 11:34 UTC, MattIPv4 requested changes
:wave: Functionality wise this is looking great, just some quick cleanup notes for the PR 💙 

---

Please could you make sure the copyright year is 2022 in all the files you've updated?

2022-06-14 11:34 UTC, MattIPv4 commented on src/nginxconfig/i18n/de/templates/global_sections/performance.js
> +    disableHtmlCaching: 'Disable HTML caching',
```suggestion
    disableHtmlCaching: 'Disable HTML caching', // TODO: translate
```

2022-06-14 11:34 UTC, MattIPv4 commented on src/nginxconfig/i18n/de/templates/global_sections/performance.js
> +    enableChangesTakeEffect: 'disable HTML caching',
```suggestion
    enableDisableHtmlCaching: 'disable HTML caching', // TODO: translate
```

2022-06-14 11:34 UTC, MattIPv4 commented on src/nginxconfig/i18n/es/templates/global_sections/performance.js
> +    enableChangesTakeEffect: 'disable HTML caching',
```suggestion
    enableDisableHtmlCaching: 'disable HTML caching', // TODO: translate
```

2022-06-14 11:34 UTC, MattIPv4 commented on src/nginxconfig/i18n/pt-br/templates/global_sections/performance.js
> +    disableHtmlCaching: 'Disable HTML caching',
```suggestion
export default {
    disableHtmlCaching: 'Disable HTML caching', // TODO: translate
```

2022-06-14 11:34 UTC, MattIPv4 commented on src/nginxconfig/i18n/zh-tw/templates/global_sections/performance.js
> +    disableHtmlCaching: 'Disable HTML caching',
```suggestion
    disableHtmlCaching: 'Disable HTML caching', // TODO: translate
```

2022-06-14 11:34 UTC, MattIPv4 commented on src/nginxconfig/i18n/zh-tw/templates/global_sections/performance.js
> +    enableChangesTakeEffect: 'disable HTML caching',
```suggestion
    enableDisableHtmlCaching: 'disable HTML caching', // TODO: translate
```

2022-06-14 11:34 UTC, MattIPv4 commented on src/nginxconfig/templates/global_sections/performance.vue
> +
```suggestion
```

2022-06-14 11:34 UTC, MattIPv4 commented on src/nginxconfig/templates/global_sections/performance.vue
> +                                {{ $t('templates.globalSections.performance.enableChangesTakeEffect') }}
```suggestion
                                {{ $t('templates.globalSections.performance.enableDisableHtmlCaching') }}
```

2022-06-14 11:34 UTC, MattIPv4 commented on src/nginxconfig/templates/global_sections/performance.vue
> -        </div>
Why has this been removed? Please revert

2022-06-14 11:34 UTC, MattIPv4 commented on src/nginxconfig/templates/global_sections/performance.vue
> +            default: true,
```suggestion
            default: false,
```
To ensure backwards compatibility in the tool, let's set this to false by default

2022-06-14 11:34 UTC, MattIPv4 commented on src/nginxconfig/util/angular_backwards_compatibility.js
> +    disableHtmlCaching:         ['performance', 'disableHtmlCaching', oldBool],
```suggestion
```
This doesn't need to be included here as this was never a feature in the Angular version of the tool

2022-06-14 11:34 UTC, MattIPv4 commented on src/nginxconfig/util/types_extensions.js
> +    html: 'html',
```suggestion
    html: 'html?',
```
Allow `html` or `htm`

2022-06-14 13:49 UTC, chenyhd commented
Done.

2022-06-14 22:05 UTC, MattIPv4 approved these changes
LGTM, tyvm

2022-06-14 22:05 UTC, merged

2022-06-17 12:16 UTC, MattIPv4 commented
Hey, @chenyhd - Thanks a ton for this sweet PR! 😄

Would you please shoot me an email when you get a chance?
mcowley at digitalocean dot com 🎉