Add Japanese translation
digitalocean/nginxconfig.io pull request #368
Opened 2022-06-14 03:29 UTC by Ippey

## Type of Change

- **Something else:** Add Japanese translation.

## What issue does this relate to?

None

### What should this PR do?

- Add Japanese translation.
- Add `ja` in each `languages.js` .

### What are the acceptance criteria?

2022-06-14 22:07 UTC, MattIPv4 commented
:wave: Hey @Ippey, would you mind updating the `Copyright xxxx` value in the files you've modified to be 2022?

I've also just merged #366 which added two new strings that your language pack will need 💙 

Tyvm!

2022-06-15 00:49 UTC, Ippey commented
@MattIPv4 I've just modified it!

2022-06-15 13:41 UTC, Ippey commented
I'm sorry. I added `disableHtmlCaching`, `enableDisableHtmlCaching`  translation in `ja`. 🙏

2022-06-15 13:56 UTC, SiderealArt commented
Hi, could you take a look at the suggestions I made above?

2022-06-15 14:31 UTC, SiderealArt commented
Yes, as @MattIPv4 said earlier.

2022-06-15 14:44 UTC, Ippey commented
@MattIPv4  I also modified every `languages.js`.

Thank you, @SiderealArt !

2022-06-15 14:57 UTC, SiderealArt commented
I forgot to click comment. I meant these suggestions. Sorry for bothering you again. 😥

2022-06-15 15:28 UTC, MattIPv4 requested changes
💙 Thank you for this translation -- a few quick thoughts:

2022-06-15 15:28 UTC, MattIPv4 commented on src/nginxconfig/i18n/ja/templates/setup_sections/go_live.js
> +    letsGoLive: 'Let\'s go live!',
Can this be translated?

2022-06-15 15:28 UTC, MattIPv4 commented on src/nginxconfig/i18n/ja/templates/setup_sections/go_live.js
> +    goLive: 'Go live!',
Can this be translated?

2022-06-15 15:28 UTC, MattIPv4 commented on src/nginxconfig/i18n/pl/languages.js
> +    ja: 'Japonês',
```suggestion
    ja: 'Japoński',
```

2022-06-15 22:38 UTC, Ippey commented
@MattIPv4 @SiderealArt Thank you for your suggestions. I corrected them.

2022-06-16 14:37 UTC, MattIPv4 approved these changes
LGTM, thank you very much for contributing this! 💙

2022-06-16 14:37 UTC, merged

2022-06-17 12:17 UTC, MattIPv4 commented
Hey, @Ippey - Thanks a ton for this sweet PR! 😄

Would you please shoot me an email when you get a chance?
mcowley at digitalocean dot com 🎉