:sparkles: feat: proxy header override
digitalocean/nginxconfig.io pull request #393
Opened 2022-10-03 06:09 UTC by MrJmpl3

## Type of Change

- **Build Scripts:** 
- **Tool Source:**  Vue -> Proxy category
- **Something else:** 

## What issue does this relate to?

https://github.com/digitalocean/nginxconfig.io/issues/382

### What should this PR do?

Move the proxy_set_header Host to per domain config

### What are the acceptance criteria?

Well, missing translations with the key 'proxyHeaderOverride', also in Spanish, I think the translation is 'Reemplazo de cabecera del proxy' or only 'Reemplazo de cabecera' because 'del proxy' is redudant.

In another languages, I don't know 😌

If all is correct, please add the tag 'hacktoberfest-accepted', Thanks

2022-10-03 06:24 UTC, MrJmpl3 commented
Oh, the test failed because the missing translation, and now? It's 'Google translate' time?

2022-10-03 12:56 UTC, MattIPv4 commented
@MrJmpl3 You can leave the strings in English in each of the i18n files and add `// TODO: translate` comments to each line (you'll find a few of these already in the i18n files)

2022-10-07 11:37 UTC, MattIPv4 requested changes
:wave: Could you make sure the copyright year is bumped in the header of any file you've touched?

2022-10-07 11:37 UTC, MattIPv4 commented on src/nginxconfig/i18n/en/templates/domain_sections/reverse_proxy.js
> +    proxyHeaderOverride: 'Proxy header override',
```suggestion
    proxyHeaderOverride: 'Proxy Host header',
```
I think we should call out the header this affects here, for clarity (it also isn't really an override given the default is `$host`).

2022-10-08 17:08 UTC, MrJmpl3 commented
> 👋 Could you make sure the copyright year is bumped in the header of any file you've touched?

Ok, I update the year of copyright

2022-10-08 17:10 UTC, MattIPv4 requested changes
👀 Two more things, sorry!

- Could apply the `'Proxy header override'` ->  `'Proxy Host header'` change to all the i18n files?
- Can you change the key we're using in all the logic from being `proxyHeaderOverride` to `proxyHostHeader`? We override quite a few headers, but this setting is specifically the host header

2022-10-08 17:15 UTC, MrJmpl3 commented
> 👀 Two more things, sorry!
> 
>     * Could apply the `'Proxy header override'` ->  `'Proxy Host header'` change to all the i18n files?
> 
>     * Can you change the key we're using in all the logic from being `proxyHeaderOverride` to `proxyHostHeader`? We override quite a few headers, but this setting is specifically the host header

ok, wait some minutes

2022-10-08 18:54 UTC, MattIPv4 approved these changes
LGTM, tyvm

2022-10-08 18:54 UTC, merged